# Generated by Django 4.0.4 on 2022-05-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedownloadermodel',
            old_name='xcel_file',
            new_name='uploaded_file',
        ),
    ]
