# Generated by Django 4.0.4 on 2022-05-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0002_rename_xcel_file_filedownloadermodel_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownloadermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='filedownloadermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
