# Generated by Django 4.0.4 on 2022-05-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0003_filedownloadermodel_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedownloadermodel',
            old_name='file_type',
            new_name='fileType',
        ),
        migrations.RenameField(
            model_name='filedownloadermodel',
            old_name='sheet_name',
            new_name='sheetName',
        ),
        migrations.RenameField(
            model_name='filedownloadermodel',
            old_name='uploaded_file',
            new_name='uploadedFile',
        ),
        migrations.AddField(
            model_name='filedownloadermodel',
            name='isFilePicked',
            field=models.BooleanField(default=False),
        ),
    ]
